CustomPost[118] = {} -- Setup Initiator
CustomPost[118].AuthorityAccount = {"Greed", "Rafael", "Ayrton"} -- list of players authorized to use the command
CustomPost[118].Global = true -- true > Global Message | false > Local Message
CustomPost[118].ShowOnChat = true -- true > show message in chat box | false > not show
CustomPost[118].ShowOnScreen = true -- true > show message on center of screen | false > not show
CustomPost[118].Message = 2005 -- message id in Message.txt
CustomPost[118].CountDown = {0, 0, 0, 0} -- delay time to use again
CustomPost[118].DiscordType = "staff" -- Type of post used in Discord
CustomPost[118].DiscordMessageId = 2009 -- message ID used by discord
