CREATE TABLE dbo.MSC_CS_SWITCH_RANKING_GUILD (
	G_Name varchar(10) NOT NULL,
	Score int DEFAULT 0 NOT NULL
);
GO

CREATE TABLE dbo.MSC_CS_SWITCH_RANKING_PLAYER (
	Name varchar(10) NOT NULL,
	Score int DEFAULT 0 NOT NULL
);
GO